In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

path = 'DATA'
data_init = pd.read_pickle(path + '/data_test_nn.pkl')

size = 100
# data = pd.concat([data_init[0:3], data_init[50])
data = data_init


data['MAX_DEBT_GRP_9M'] = data['MAX_DEBT_GRP_9M'].fillna(-2)

var = ['MAX_DEBT_GRP_9M', 'AMT_AVAIL_LIAB']

X = data[var].to_numpy()
Y = data['BAD'].to_numpy()

X_init = X.copy()
Y_init = Y.copy()

In [2]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-2,3))
X = scaler.fit_transform(X)

In [3]:
#Setup layers
layers = [2,3,3,1]

In [22]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_derivative(x):
    return x*(1-x)

[<tf.Variable 'dense_18/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 0.5631693 , -0.67108387,  0.5104649 ],
        [ 1.3093847 , -0.16734126, -1.0386293 ]], dtype=float32)>,
 <tf.Variable 'dense_18/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_19/kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.51410085, -0.61261296,  0.46598858],
        [ 1.1952993 , -0.15276097, -0.94813454],
        [-0.7538571 , -0.11811214, -0.5824808 ]], dtype=float32)>,
 <tf.Variable 'dense_19/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_20/kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[ 0.62964237],
        [-0.75029457],
        [ 0.5707171 ]], dtype=float32)>,
 <tf.Variable 'dense_20/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [5]:
#learning rate 
alpha = 0.1

In [19]:
def fit_partial(X, Y):
    A = [X]
    out = A[-1]
    for i in range(0, len(layers) - 1):
        out = sigmoid(np.dot(out, W[i]) + (b[i].T))
        A.append(out)
    ##backpropagation
    Y = Y.reshape(-1, 1)
    dA = [-(Y/A[-1] - (1-Y)/(1-A[-1]))]
#     print(type(dA)) 
    dW = []
    db = []
    for i in reversed(range(0, len(layers)-1)):
        dw_ = np.dot((A[i]).T, dA[-1] * sigmoid_derivative(A[i+1]))
        db_ = (np.sum(dA[-1] * sigmoid_derivative(A[i+1]), 0)).reshape(-1,1)
        dA_ = np.dot(dA[-1] * sigmoid_derivative(A[i+1]), W[i].T)
        dW.append(dw_)
        db.append(db_)
        dA.append(dA_)
    #Đảo dW, db
    dW = dW[::-1]
    db = db[::-1]
    # Gradient descent
    for i in range(0, len(layers)-1):
        W[i] = W[i] - alpha * dW[i]
        b[i] = b[i] - alpha * db[i]
    return W,b

def predict(X):
    for i in range(0, len(layers) - 1):
        X = sigmoid(np.dot(X, W[i]) + (b[i].T))
    return X

def calculate_loss(X, y):
    y_predict = predict(X)
    return -(np.sum(y.reshape(y.shape[0],1)*np.log(y_predict) + (1-y).reshape(y.shape[0],1)*np.log(1-y_predict))) / y.shape[0]

def fit(X, y, epochs, verbose):
    t = []
    l = []
    for epoch in range(0, epochs):
        t.append(epoch)
        fit_partial(X, y)
        loss = calculate_loss(X, y)
        l.append(loss)
#         print(X,' ', y)
        print("Epoch {}, loss {}".format(epoch, loss))
#     plt.plot(t,l)
#     plt.show()
#     print(W,b)

In [7]:
W = [np.array([[ 0.5631693 , -0.67108387,  0.5104649 ], [ 1.3093847 , -0.16734126, -1.0386293 ]]),
     np.array([[ 0.51410085, -0.61261296,  0.46598858], [ 1.1952993 , -0.15276097, -0.94813454], [-0.7538571 , -0.11811214, -0.5824808 ]]),
     np.array([[ 0.62964237], [-0.75029457], [ 0.5707171 ]])]
b = [np.array([[0], [0], [0]]), np.array([[ 0], [0], [0]]), np.array([[0.]])]

for i in range(size):
    fit(X=X[i:i+1], y=Y[i:i+1], epochs=1, verbose=1)

Epoch 0, loss 0.8764251143891951
Epoch 0, loss 0.8099371509996431
Epoch 0, loss 0.6765420030311203
Epoch 0, loss 0.6435519874478905
Epoch 0, loss 0.6706774870740889
Epoch 0, loss 0.5192485772707838
Epoch 0, loss 0.49147248054599835
Epoch 0, loss 0.5546107022063455
Epoch 0, loss 0.5255920520686345
Epoch 0, loss 0.41923051765388303
Epoch 0, loss 0.3926333491935201
Epoch 0, loss 0.38030795892199837
Epoch 0, loss 0.3630107656370107
Epoch 0, loss 0.3970849812635354
Epoch 0, loss 0.33209487345820715
Epoch 0, loss 0.3187931448148569
Epoch 0, loss 0.3031054191096652
Epoch 0, loss 0.28826485516738937
Epoch 0, loss 0.27836189477307055
Epoch 0, loss 0.2671314059644178
Epoch 0, loss 0.258633346636753
Epoch 0, loss 0.248381483161971
Epoch 0, loss 0.2397804962700114
Epoch 0, loss 0.2388779430369743
Epoch 0, loss 0.22594598845978417
Epoch 0, loss 0.21825064484815754
Epoch 0, loss 0.2237929793543156
Epoch 0, loss 0.20895129135006968
Epoch 0, loss 0.19912850147113148
Epoch 0, loss 0.1933960787875195
Ep

In [8]:
calculate_loss(X, Y)

1.0237062110657302

In [9]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC
from tensorflow.keras.optimizers import SGD

init = tf.keras.initializers.GlorotNormal(seed=123)

In [10]:
learning_rate = 0.1
model = tf.keras.Sequential([
    tf.keras.layers.Dense(3, input_shape=(X.shape[1],), activation='sigmoid',kernel_initializer=init),
    tf.keras.layers.Dense(3, activation='sigmoid',kernel_initializer=init),
    tf.keras.layers.Dense(1, activation='sigmoid',kernel_initializer=init)
])

model.compile(optimizer=SGD(learning_rate=0.1), loss='binary_crossentropy')

In [11]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 0.5631693 , -0.67108387,  0.5104649 ],
        [ 1.3093847 , -0.16734126, -1.0386293 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.51410085, -0.61261296,  0.46598858],
        [ 1.1952993 , -0.15276097, -0.94813454],
        [-0.7538571 , -0.11811214, -0.5824808 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[ 0.62964237],
        [-0.75029457],
        [ 0.5707171 ]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 9         
                                                                 
 dense_1 (Dense)             (None, 3)                 12        
                                                                 
 dense_2 (Dense)             (None, 1)                 4         
                                                                 
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(X, Y, epochs=1, batch_size=1, shuffle=False)

100/100 [==============================] - 0s 876us/step - loss: 0.4983


In [14]:
model.evaluate(X, Y, batch_size=1)

100/100 [==============================] - 0s 765us/step - loss: 1.0237


1.023706316947937

In [17]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 0.6725793 , -0.687065  ,  0.49847677],
        [ 1.2153368 , -0.16997623, -1.0133688 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(3,) dtype=float32, numpy=array([ 0.04090656,  0.00107377, -0.01050736], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.5249595 , -0.6253261 ,  0.48223156],
        [ 1.2448055 , -0.13000713, -0.9026431 ],
        [-0.6368713 , -0.3336208 , -0.4305315 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(3,) dtype=float32, numpy=array([ 0.11473031, -0.13188489,  0.13893947], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[ 0.9252008 ],
        [-0.39796114],
        [ 0.86730605]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.90197116], dtype=float32)>]

In [114]:
W

[array([[ 0.67257958, -0.68706499,  0.49847667],
        [ 1.21533657, -0.16997617, -1.01336864]]),
 array([[ 0.52495945, -0.62532626,  0.48223147],
        [ 1.24480524, -0.13000709, -0.9026433 ],
        [-0.63687133, -0.33362074, -0.43053157]]),
 array([[ 0.92520068],
        [-0.39796104],
        [ 0.867306  ]])]

In [84]:
b

[array([[-0.00169272],
        [-0.00101954],
        [ 0.00143463]]),
 array([[-0.01861177],
        [ 0.03023618],
        [-0.0210513 ]]),
 array([[-0.17032798]])]

### Test mẫu nhỏ

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_pickle('./data_test_nn.pkl')
data.head()

CIF  MAX_DEBT_GRP_9M  AMT_AVAIL_LIAB  BAD
0  4824585             -1.0     72870429.83  0.0
1  4824586             -1.0     72960000.95  0.0
2  4824587             -1.0     31920903.02  0.0
3  4824589              NaN     40008609.78  0.0
4  4824603             -1.0     96552065.93  0.0

In [4]:
data['MAX_DEBT_GRP_9M'] = data['MAX_DEBT_GRP_9M'].fillna(-2)

In [48]:
test = data.iloc[[0,1,2,51,52]]
test

CIF  MAX_DEBT_GRP_9M  AMT_AVAIL_LIAB  BAD
0   4824585             -1.0     72870429.83  0.0
1   4824586             -1.0     72960000.95  0.0
2   4824587             -1.0     31920903.02  0.0
51  4824862              2.0      4434012.32  1.0
52  4825573              2.0        13728.44  1.0

In [49]:
var = ['MAX_DEBT_GRP_9M', 'AMT_AVAIL_LIAB']

In [50]:
X = test[var].to_numpy()
Y = test['BAD'].to_numpy()

In [51]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-2,3))
X = scaler.fit_transform(X)
X

array([[-2.        ,  2.99386047],
       [-2.        ,  3.        ],
       [-2.        ,  0.18703256],
       [ 3.        , -1.69701784],
       [ 3.        , -2.        ]])

In [10]:
import numpy as np
X = np.round(X,2)
X

array([[-2.  ,  2.99],
       [-2.  ,  3.  ],
       [-2.  ,  0.19],
       [ 3.  , -1.7 ],
       [ 3.  , -2.  ]])

In [11]:
Y

array([0., 0., 0., 1., 1.])

In [52]:
layers=[2,2,2,1]

In [53]:
W = [np.array([[ 0.62964237, -0.75029457], [ 0.5707171 ,  1.4639367 ]]),
     np.array([[ 0.62964237, -0.75029457],[ 0.5707171 ,  1.4639367 ]]),
     np.array([[ 0.7270484 ],[-0.86636555]])]
b = [np.array([[0], [0]]), np.array([[ 0], [0]]), np.array([[0.]])]

In [54]:
size = 5
alpha = 0.1
for i in range(size):
    fit(X=X[i:i+1], y=Y[i:i+1], epochs=1, verbose=1)

Epoch 0, loss 0.5920758749529749
Epoch 0, loss 0.5491476241583364
Epoch 0, loss 0.49276135058005854
Epoch 0, loss 0.7052355516842326
Epoch 0, loss 0.667359543750936


In [55]:
calculate_loss(X, Y)

0.6157974643314569

### Library

In [42]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC
from tensorflow.keras.optimizers import SGD

init = tf.keras.initializers.GlorotNormal(seed=123)

In [56]:
learning_rate = 0.1
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, input_shape=(X.shape[1],), activation='sigmoid',kernel_initializer=init),
    tf.keras.layers.Dense(2, activation='sigmoid',kernel_initializer=init),
    tf.keras.layers.Dense(1, activation='sigmoid',kernel_initializer=init)
])

model.compile(optimizer=SGD(learning_rate=0.1), loss='binary_crossentropy')

In [57]:
model.weights

[<tf.Variable 'dense_15/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.62964237, -0.75029457],
        [ 0.5707171 ,  1.4639367 ]], dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_16/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.62964237, -0.75029457],
        [ 0.5707171 ,  1.4639367 ]], dtype=float32)>,
 <tf.Variable 'dense_16/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_17/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[ 0.7270484 ],
        [-0.86636555]], dtype=float32)>,
 <tf.Variable 'dense_17/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [58]:
model.fit(X, Y, epochs=1, batch_size=1, shuffle=False)

5/5 [==============================] - 0s 2ms/step - loss: 0.6438


In [59]:
model.evaluate(X, Y, batch_size=1)

5/5 [==============================] - 0s 1ms/step - loss: 0.6158


0.6157975196838379

In [60]:
model.predict(X)

1/1 [==============================] - 0s 45ms/step


array([[0.44606495],
       [0.4461092 ],
       [0.4326131 ],
       [0.5150875 ],
       [0.5130615 ]], dtype=float32)